### ISSUE TITLE
An important update for the package 'python-memoization'

### ISSUE THREAD

**Issue by lonelyenvoy** [Fazzani/pliptvcli#1]
Hi,

I am the developer of the package [`python-memoization`](https://github.com/lonelyenvoy/python-memoization) which you used in your project. Thanks for your interest in my work.

I have just published [a new version](https://github.com/lonelyenvoy/python-memoization/releases) which fixed some [bugs](https://github.com/lonelyenvoy/python-memoization/issues/2). This is an important update which enhances your program's performance. Please consider upgrading by `pip install memoization --upgrade` and change the version from `memoization==0.1.4` to `memoization==0.2.2` in [`requirements.txt`](https://github.com/Fazzani/pliptvcli/blob/7e8a1f1ebebea84250dc6ce901db8c0924c2a320/requirements.txt#L10).

Enjoy!

**Comment by Fazzani** [comment]
I will do it soon
Thank you !
