### ISSUE TITLE
some issues trying to run

### ISSUE THREAD

**Issue by selmen2004** [Fazzani/pliptvcli#4]
I am not expert on python so maybe I am missing something , sorry for that 
but even after updating , same issue on #3  : 
![image](https://user-images.githubusercontent.com/3520243/82283679-fbf89700-998e-11ea-8ccd-942025a4494a.png)

also , I need to manually create log folder to bypass another error 

![image](https://user-images.githubusercontent.com/3520243/82283764-33ffda00-998f-11ea-869b-0bd059ee2f11.png)

finally , when trying to install as module , I got this error  : 
![image](https://user-images.githubusercontent.com/3520243/82283831-66a9d280-998f-11ea-904f-0ece0e4a3d6f.png)

Thanks

**Comment by Fazzani** [comment]
Try run it as this:

PL="**https://your_playlist_url**" python main.py --auto

**Comment by selmen2004** [comment]
works 
![image](https://user-images.githubusercontent.com/3520243/82584241-1f3c6580-9b8c-11ea-83e0-dbca9873fe2c.png)
